
$(function() {

    // Populate using an object literal
    WTF.init({
        "heading": [
            "How about:",
            "What about:",
            "Hey, you should write about:",
            "Try writing about:",
            "I know, how about:"
        ],

        "response": [
            "Ugh, I've read this somewhere before. Next!",
            "Yawn, boring!",
            "I think I seen this before",
            "Don't you have anything else?",
            "That's such a lame idea.",
            "I think the admissions officers have seen this before",
            "That's so cliché.",
            "Nahh... it doesn't seem like something I'd write about."
        ],

        "template": [
            "what made you @made_you_emotions when you were in @time",
            "what made you @made_you_emotions when you were @prep_sub",
            "Imagine you were a(n) @object. What would you do? How would you feel?",
            "Describe a time when you were @made_you_emotions",
            "What do you think would make a(n) @object @made_you_emotions",
            "Describe your favorite @object",
            "Imagine @per_evt with @hist_fig. What would you do? What would you two talk about?"

        ],

        "made_you_emotions": [
            "happy",
            "well",
            "okay",
            "very well",
            "clean",
            "strong",
            "beautiful",
            "excited",
            "attracted",
            "empowered",
            "intelligent",
            "smarter",
            "better",
            "brave",
            "calm",
            "delightful",
            "eager",
            "jolly",
            "joyful",
            "kind",
            "nice",
            "sweet",
            "proud",
            "relieved",
            "hopeful",
            "faithful",
            "optimistic",
            "loving",
            "open",
            "understanding",
            "amazed",
            "great",
            "lucky",
            "fortunate",
            "festive",
            "moody",
            "playful",
            "animated",
            "wonderful",
            "thrilled",
            "supportive",
            "inspired",
            "demotivated",
            "upset",
            "shocked",
            "enraged",
            "encouraged",
            "amused",
            "relaxed",
            "confused",
            "shameful",
            "wonderful",
            "thrilled",
            "serene",
            "free",
            "liberated",
            "engrossed",
            "involved",
            "hungry",
            "tired",
            "weak",
            "disgruntled",
            "defeated",
            "embarrassed",
            "foolish",
            "silly",
            "hurt",
            "nervous",
            "bashful",
            "joyful",
            "appreciative",
            "tearful",
            "devastated",
            "horrified",
            "annoyed",
            "melancholic",
            "guilty",
            "jealous",
            "frustrated",
            "selfish",
            "overwhelmed"
        ],

        "time": [
            "kindergarten",
            "first grade",
            "second grade",
            "third grade",
            "fourth grade",
            "fifth grade",
            "sixth grade",
            "seventh grade",
            "eighth grade",
            "ninth grade",
            "tenth grade",
            "eleventh grade",
            "twelfth grade",
            "freshman year",
            "sophomore year",
            "junior year",
            "senior year",
        ],

        "prep_sub": [
            "a child",
            "in school",
            "at home",
            "away from home",
            "out of school",
            "in a car",
            "in a bus",
            "in a plane",
            "in your favorite club",
            "with your best friends",
            "with your parents",
            "with your grandparents",
            "with your favorite teacher",
        ],

        "tones": [
            "fresh",
            "bold",
            "happy",
            "devoted",
            "loving",
            "sympathetic",
            "believing",
            "supportive",
            "enlightened",
            "clever",
            "involved",
            "intent"
        ],

        "object": [
            "glassware",
            "cook book",
            "pot",
            "mixing bowl",
            "tupperware",
            "ziplock bag",
            "water pitcher",
            "magazine",
            "newspaper",
            "book",
            "make-up",
            "hair clip",
            "CD",
            "DVD",
            "candle",
            "crystal",
            "vase",
            "computer",
            "smartphone",
            "MP3 Player",
            "furniture",
            "video game",
            "shirt",
            "short",
            "pants",
            "coat",
            "dress",
            "hat",
            "shoe",
            "sandal",
            "boot",
            "jewelry",
            "purse",
            "coin",
            "cash",
            "pillow",
            "linen set",
            "candle holder",
            "TV",
            "magnet",
            "artwork",
            "pen",
            "pencil",
            "old battery",
            "duck tape",
            "masking tape",
            "manual",
            "coupon",
            "broom",
            "rake",
            "leaf",
            "garden hose",
            "board game",
            "puzzles",
            "deck of cards",
            "old school book/papers",
            "toy",
            "stuffed animal",
            "soda",
            "Amazon Kindle",
            "camera",
            "scanner",
            "GPS device",
            "road map",
            "notebook",
            "voice recorder",
            "grocery list",
            "iPod",
            "iPad",
            "radio",
            "comic book",
            "paper receipt",
            "business card"
        ],

        "hist_fig": [
            "Napoleon",
            "Shakespeare",
            "Abraham Lincoln",
            "George Washington",
            "Aristotle",
            "Alexander the Great",
            "Henry VIII of England",
            "Charles Darwin",
            "Elizabeth I of England",
            "Julius Caesar",
            "Queen Victoria",
            "Martin Luther",
            "Albert Einstein",
            "Christopher Columbus",
            "Issac Newton",
            "Charlemagne",
            "Theodore Roosevelt",
            "Wolfgang Amadeus Mozart",
            "Plato",
            "Louis XIV of France",
            "Ludwig van Beethoven",
            "Ulysses S. Grant",
            "Leonardo da Vinci",
            "Augustus",
            "Carl Linnaeus",
            "Ronald Reagan",
            "Charles Dickens",
            "Benjamin Franklin",
            "Genghis Khan",
            "Charles I of England",
            "Thomas Edison",
            "James I of England",
            "Friedrich Nietzsche",
            "Franklin D. Roosevelt",
            "Sigmund Freud",
            "Alexander Hamilton",
            "Mohandas K. Ghandhi",
            "Woodrow Wilson",
            "J. S. Bach",
            "Galileo Galilei",
            "Oliver Cromwell",
            "James Madison",
            "Mark Twain",
            "Edgar Allan Poe",
            "Joseph Smith, Jr.",
            "Adam Smith",
            "George III of the United Kingdom",
            "Immanuel Kant",
            "James Cook",
            "John Adams",
            "Richard Wagner",
            "Pyotr Ilyich Tchaikovsky",
            "Voltaire",
            "Andrew Jackson",
            "Constantine the Great",
            "Socrates",
            "Elvis Presley",
            "William the Conqueror",
            "John F. Kennedy",
            "Augustine of Hippo",
            "Vincent van Gogh",
            "Nicolaus Copernicus",
            "Robert E. Lee",
            "Oscar Wilde",
            "Charles II of England",
            "Cicero",
            "Jean-Jacques Rousseau",
            "Francis Bacon",
            "Richard Nixon",
            "Louis XVI of France",
            "Charles V, Holy Roman Emperor",
            "King Arthur",
            "Michelangelo",
            "Philip II of Spain",
            "Thomas Aquinas",
            "René Descartes",
            "Nikola Tesla",
            "Harry S. Truman",
            "Dante Alighieri",
            "John Calvin",
            "John Locke",
            "Henry David Thoreau"
        ],

        "per_evt": [
            "at a party",
            "breakfast",
            "lunch",
            "dinner",
            "having tea with",
            "at Starbucks with",
            "in a meeting",
            "being in a college interview",
            "in class",
            "on a Skype call",
            "being in a Google Hangout",
            "in a car ride",
            "in the library",
            "at a resturant",
            "at a diner",
            "in a conference call",
            "hanging out",
            "walking in the park",
            "jogging",
            "studying with",
            "in a book club"
        ]
    });

});
